export const PLACEHOLDER_GIF = "https://placehold.co/900x560/febdcd/111111?text=Replace+GIF+Here";
      { id: "dayA-11", name: "Plank", detail: "2 min", tip: "Keep body long and steady.", label: "finisher", visual: PLACEHOLDER_GIF },
      { id: "dayA-12", name: "Stretch Chest + Shoulders", detail: "20 to 30 sec", tip: "Breathe and let the upper body relax.", label: "stretch", visual: PLACEHOLDER_GIF },
    ],
  },
  dayB: {
    key: "dayB",
    title: "Day B: Back + Arms",
    shortTitle: "Day B",
    description: "A home back-and-arms day for posture support, upper-body shape, and arm definition.",
    goal: "Stronger back, more arm definition, and a broader-looking silhouette.",
    steps: [
      { id: "dayB-1", name: "Arm Circles", detail: "30 sec", tip: "Start small, then go a little bigger.", label: "warm-up", visual: PLACEHOLDER_GIF },
      { id: "dayB-2", name: "Shoulder Rolls", detail: "10 forward + 10 backward", tip: "Keep neck relaxed.", label: "warm-up", visual: PLACEHOLDER_GIF },
      { id: "dayB-3", name: "Dumbbell Rows", detail: "12 each side", tip: "Pull toward your hip, not your chest.", label: "workout", visual: PLACEHOLDER_GIF },
      { id: "dayB-4", name: "Rest", detail: "60 sec", tip: "Shake out the arms and breathe.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dayB-5", name: "Reverse Fly", detail: "12 reps", tip: "Open wide and gently squeeze upper back.", label: "workout", visual: PLACEHOLDER_GIF },
      { id: "dayB-6", name: "Rest", detail: "60 sec", tip: "Relax shoulders.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dayB-7", name: "Hammer Curls", detail: "15 reps", tip: "Keep wrists neutral and elbows close.", label: "workout", visual: PLACEHOLDER_GIF },
      { id: "dayB-8", name: "Rest", detail: "60 sec", tip: "Breathe and reset grip.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dayB-9", name: "Cross-body Hammer Curls", detail: "12 each side", tip: "Move slowly across the body.", label: "workout", visual: PLACEHOLDER_GIF },
      { id: "dayB-10", name: "Rest", detail: "60 sec", tip: "Relax arms before triceps.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dayB-11", name: "Overhead Tricep Extensions", detail: "12 to 15 reps", tip: "Keep elbows mostly forward and steady.", label: "workout", visual: PLACEHOLDER_GIF },
      { id: "dayB-12", name: "Rest", detail: "60 sec", tip: "Unclench shoulders and jaw.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dayB-13", name: "Superman Hold", detail: "20 to 30 sec", tip: "Lift gently through chest and legs.", label: "finisher", visual: PLACEHOLDER_GIF },
      { id: "dayB-14", name: "Stretch Upper Back + Arms", detail: "20 to 30 sec", tip: "Breathe and soften tension.", label: "stretch", visual: PLACEHOLDER_GIF },
    ],
  },
  dailyAddon: {
    key: "dailyAddon",
    title: "Daily Add-On",
    shortTitle: "Add-On",
    description: "A small bonus quest for extra momentum on good-energy days.",
    goal: "Quick upper-body support without making the routine feel heavy.",
    steps: [
      { id: "dailyAddon-1", name: "Push-ups or Incline Push-ups", detail: "10 reps", tip: "Choose incline if form feels better.", label: "bonus", visual: PLACEHOLDER_GIF },
      { id: "dailyAddon-2", name: "Rest", detail: "30 sec", tip: "Small breath reset.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "dailyAddon-3", name: "Lateral Raises", detail: "10 reps", tip: "Lift only to shoulder height.", label: "bonus", visual: PLACEHOLDER_GIF },
      { id: "dailyAddon-4", name: "Wall Chest Opener Stretch", detail: "20 sec", tip: "Open the front of the shoulders and breathe.", label: "stretch", visual: PLACEHOLDER_GIF },
    ],
  },
  postureCheck: {
    key: "postureCheck",
    title: "Posture Check",
    shortTitle: "Posture",
    description: "A guided posture flow to help you feel supported, open, and more aligned.",
    goal: "Comfort, structure, and a steadier upper-body shape.",
    steps: [
      { id: "postureCheck-1", name: "Stand Tall", detail: "10 sec", instruction: "Stand with feet hip-width apart.", feel: "Stable and grounded.", avoid: "Locking your knees.", tip: "Start by simply taking up your space.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-2", name: "Soften Knees", detail: "10 sec", instruction: "Keep a tiny bend in your knees.", feel: "Relaxed, not stiff.", avoid: "Standing rigid.", tip: "A softer base helps the upper body settle better.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-3", name: "Roll Shoulders Up, Back, Down", detail: "3 slow reps", instruction: "Lift shoulders slightly, roll them back, then let them settle down.", feel: "Shoulder blades resting gently.", avoid: "Pinching too hard.", tip: "Aim for open and supported, not forced.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-4", name: "Chest Neutral", detail: "10 sec", instruction: "Let your chest feel open but not exaggerated.", feel: "Calm and supported.", avoid: "Puffing too much or collapsing forward.", tip: "Neutral usually feels better than overcorrecting.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-5", name: "Ribs Over Hips", detail: "10 sec", instruction: "Keep ribcage stacked over hips.", feel: "Balanced through the middle.", avoid: "Leaning back.", tip: "Think steady, not stiff.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-6", name: "Chin Tuck", detail: "3 gentle reps", instruction: "Pull chin slightly back like making a soft double chin.", feel: "Long back of neck.", avoid: "Tilting head upward.", tip: "Gentle is enough here.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-7", name: "Three Slow Breaths", detail: "3 breaths", instruction: "Inhale slowly, exhale slowly.", feel: "Grounded and calm.", avoid: "Lifting shoulders while breathing.", tip: "Let the breath soften the body.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "postureCheck-8", name: "Hold Posture", detail: "20 to 30 sec", instruction: "Stay tall and breathe normally.", feel: "Aligned, calm, steady.", avoid: "Tensing too hard.", tip: "Supportive posture should feel kind, not punishing.", label: "stretch", visual: PLACEHOLDER_GIF },
    ],
  },
  deskJobFix: {
    key: "deskJobFix",
    title: "Desk Job Fix",
    shortTitle: "Desk Fix",
    description: "A quick 2 to 5 minute reset for stiffness, posture, and energy.",
    goal: "Uncurl, move, and reset your upper-body shape after sitting.",
    steps: [
      { id: "deskJobFix-1", name: "Stand Up", detail: "10 sec", tip: "Step away from the chair and uncurl.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-2", name: "March in Place", detail: "30 sec", tip: "Swing arms lightly and wake up the body.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-3", name: "Bodyweight Squats", detail: "10 reps", tip: "Sit back gently and stand tall.", label: "mobility", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-4", name: "Rest", detail: "30 sec", tip: "Let breathing settle.", label: "rest", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-5", name: "Arm Raises", detail: "10 reps", tip: "Reach up with control, lower slowly.", label: "mobility", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-6", name: "Chest Opener Stretch", detail: "20 sec", tip: "Open the front of the shoulders and breathe.", label: "stretch", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-7", name: "Hip Flexor Stretch Left", detail: "20 sec", tip: "Keep torso upright and feel the front of the hip open.", label: "stretch", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-8", name: "Hip Flexor Stretch Right", detail: "20 sec", tip: "Same on the other side.", label: "stretch", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-9", name: "Shoulder Rolls", detail: "10 reps", tip: "Let neck and shoulders soften.", label: "reset", visual: PLACEHOLDER_GIF },
      { id: "deskJobFix-10", name: "Shake Out + Reset Posture", detail: "15 sec", tip: "Relax arms, then stand tall again.", label: "reset", visual: PLACEHOLDER_GIF },
    ],
  },
} as const;

export const flowOrder = ["dayA", "dayB", "dailyAddon", "postureCheck", "deskJobFix"] as const;
export const dailyDefaults = { steps: false, plank: false, posture: false, deskFix: false, addon: false };
export const timerPresets = [20, 30, 60, 120, 300];
